map_type: costmap

obstacle_range: 4.0
raytrace_range: 5.0

transform_tolerance: 0.2

inflation_radius: 0.2

controller_frequency: 5.0

cost_scaling_factor: 10

footprint:  [[-0.125, 0.162], [0.162, 0.125], [0.162, -0.125], [-0.125, -0.162]]
#[[-height, width], [width, height], [width, -height], [-height, -width]] 

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}