<?xml version="1.0" encoding="UTF-8" ?>

<robot 
  name="custom_bot"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!--  -->
  <xacro:include filename="$(find udacity_bot)/urdf/custom_bot.gazebo" />
  <xacro:include filename="$(find udacity_bot)/urdf/wheels.xacro" />

  <!-- Parameterized robot dimensions -->
  <xacro:property name="wheel_radius" value="0.052" />
  <xacro:property name="wheel_width" value="0.055" />
  <xacro:property name="wheel_base" value="0.242" />
  <xacro:property name="spur_width" value="0.112" />

  <xacro:property name="chassis_width" value="0.162" />
  <xacro:property name="chassis_length" value="0.367" />
  <xacro:property name="chassis_height" value="0.125" />
  <xacro:property name="chassis_clearance" value="0.060" />
  <xacro:property name="chassis_mass" value="10" />

  <link name="robot_footprint"/>
 
  <joint name="robot_footprint_joint" type="fixed">
    <parent link="robot_footprint"/>
    <child link="chassis" />
    <origin xyz="0 0 ${chassis_height/2}"/>
  </joint>


  <link name="chassis">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="LightBlue">
        <color rgba="0.4 0.4 1.0 1.0" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chassis_mass}" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
    </inertial>
  </link>
  <gazebo reference="chassis" >
    <material>Gazebo/Orange</material>
  </gazebo> 

  <xacro:wheel prefix="left"  suffix="front" reflect="1" mirror="1"/>
  <xacro:wheel prefix="right" suffix="front" reflect="-1" mirror="1"/>
  <xacro:wheel prefix="left"  suffix="rear"  reflect="1" mirror="-1"/>
  <xacro:wheel prefix="right" suffix="rear"  reflect="-1" mirror="-1"/>

  <link name="camera">
    <collision>
      <origin xyz="-0.005 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.03 0.03"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.005 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.03 0.03"/>
      </geometry>
    </visual>

    <inertial>
      <mass value=".1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <link name="hokuyo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".01 .01 .01"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://udacity_bot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value=".1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="base_to_camera" type="fixed">
    <parent link="chassis" />
    <child link="camera" />
    <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
  </joint>

  <joint name="hokuyo_joint" type="fixed">
    <parent link="chassis"/>
    <child link="hokuyo"/>
    <origin rpy="0 0 0" xyz="0 0 ${chassis_height/2+0.03}"/>
    <axis xyz="0 1 0" />
  </joint>

  
  
</robot>
