<?xml version="1.0"?>
<robot
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  >
  <!--
    Wheel definition.
    Parameters:
    prefix suffix reflect mirror
    Properties:
    wheel_width
    wheel_radius
    wheel_base
    spur_width
    chassis_clearance
   -->
  <xacro:macro name="wheel" params="prefix suffix reflect mirror">
    <link name="${prefix}_${suffix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="2.637" />
        <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
        <inertia  ixx="0.02467" ixy="0" ixz="0" iyy="0.04411" iyz="0" izz="0.02467" />
      </inertial>
    </link>
    <gazebo reference="${prefix}_${suffix}_wheel_link">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <fdir1 value="0 1 0"/>
      <material>Gazebo/Black</material>
    </gazebo>
    <transmission name="${prefix}_${suffix}_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_to_${prefix}_${suffix}_wheel">
            <hardwareInterface>VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="${prefix}_${suffix}_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <joint name="base_to_${prefix}_${suffix}_wheel" type="continuous">
      <parent link="robot_footprint" />
      <child link="${prefix}_${suffix}_wheel_link" />
      <origin xyz="${wheel_base/2*mirror}  ${spur_width*reflect} ${wheel_radius-chassis_clearance}" rpy="0 0 ${(pi/2)}" />
      <limit effort="10000" velocity="1000"/>
      <joint_properties damping="1.0" friction="1.0"/>
    </joint>
  </xacro:macro>


</robot>
